version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - .:/app
    networks:
      redis_net:
      nginx_net:
    restart: always
    ports:
      - 8000:8000

networks:
  redis_net:
    name: redis_net
  nginx_net:
    name: nginx_net
    external: true
#
#  redis:
#    container_name: redis
#    image: redis
#    restart: always
#    ports:
#      - 6379:6379
#    networks:
#      - redis
#
#networks:
#  5letters:
#    name: network
#  redis:
#    name: network