version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - .:/app
    restart: always
    ports:
      - 80:8000
    networks:
      - 5letters

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - redis

networks:
  5letters:
    name: network
  redis:
    name: network